# Solana Snapshot Monitor Configuration

# Directory to monitor for snapshots
watch_dir: "/snapshots"

# S3-compatible storage configuration
s3_endpoint: "https://s3.example.com"
s3_bucket: "solana-snapshots"
s3_access_key: "your-access-key"
s3_secret_key: "your-secret-key"

# Solana configuration
# solana_version: "1.18.5"  # Optional, auto-detected if not specified
solana_rpc_url: "http://localhost:8899"  # Used to auto-detect Solana version and feature set

# Minimum slot gap between full snapshots
full_snapshot_gap: 25000

# Maximum slot gap for incremental snapshots
incremental_gap: 500

# Enable or disable incremental snapshot uploads (true/false)
enable_incremental_snap: true

# Retention settings
enable_retention: true  # Enable automatic deletion of old snapshots
# retention_period_hours: 168  # Legacy: Delete snapshots older than 7 days

# Full snapshot retention (count and time-based)
full_snapshot_retain_count: 3  # Keep at least this many recent full snapshots
full_snapshot_retain_hours: 168  # Keep full snapshots for 28 days (4 weeks)

# Incremental snapshot retention (count and time-based)
incremental_retain_count: 5  # Keep at least this many recent incremental snapshots per full snapshot
incremental_retain_hours: 24  # Keep incremental snapshots for 7 days (1 week)

# Log level (debug, info, warn, error)
log_level: "info"

# Hostname to identify this instance (optional, auto-detected if not specified)
hostname: "node-1"
