version: '3'
services:
  snapshot-monitor:
    image: ghcr.io/blockdaemon/agave-snapshot-uploader:latest
    restart: always
    environment:
      WATCH_DIR: "/snapshots"
      S3_ENDPOINT: "https://s3.example.com"
      S3_BUCKET: "solana-snapshots"
      S3_NAMESPACE: "mainnet"
      S3_ACCESS_KEY: "your-access-key"
      S3_SECRET_KEY: "your-secret-key"
      S3_PUBLIC_ENDPOINT: "https://s3.example.com"
      SOLANA_VERSION: "1.18.5"
      SOLANA_RPC_URL: "http://localhost:8899"
      FULL_SNAPSHOT_GAP: "25000"
      INCREMENTAL_GAP: "500"
      ENABLE_INCREMENTAL_SNAP: "true"
      ENABLE_RETENTION: "true"
      FULL_SNAPSHOT_RETAIN_COUNT: "3"
      FULL_SNAPSHOT_RETAIN_HOURS: "168"
      INCREMENTAL_RETAIN_COUNT: "5"
      INCREMENTAL_RETAIN_HOURS: "24"
      LOG_LEVEL: "info"
      HOSTNAME: "node-1"
    volumes:
      - /data/snapshots:/snapshots
